repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 23.11.0  
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0  
    hooks:
    - id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  
    hooks:
    - id: flake8
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17  
    hooks:
    - id: mdformat
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0  
    hooks:
    - id: mypy
      files: ^src/
      args: []
-   repo: https://github.com/pytest-dev/pytest
    rev: v7.0.1  
    hooks:
    - id: pytest
